name: 'Issue assigner'
on:
  issues:
    types: [opened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: patrickhulce/issue-assigner@eeec7a10bd3c02f02d2284fc82a8adabdc001869
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          maintainers: 'paulirish,connorjclark,adamraine,brendankenny'
